name: Continuous build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'

jobs:
  release-apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          channel: 'stable'
      - run: |
          flutter --no-color build apk
          mv build/app/outputs/flutter-apk/app-release.apk ./flauncher-continuous-release.apk
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flauncher-continuous-release
          path: ./flauncher-continuous-release.apk
          retention-days: 30
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        run: |
          gh release delete continuous --yes
          gh release create continuous --title "Continuous release" ./flauncher-continuous-release.apk
        
