name: Continuous build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'

jobs:
  release-apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          channel: 'stable'
      - run: |
          flutter --no-color build apk
          mv build/app/outputs/flutter-apk/app-release.apk ./flauncher-continuous-release.apk
      - name: Continuous release
        env:
          GH_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        run: gh release create continuous ./flauncher-continuous-release.apk
        
