name: Continuous build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'

jobs:
  release-apk:
    name: Release APK
    env:
      OUTPUT_DIR: 'build/app/outputs/flutter-apk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          channel: 'stable'
      - name: Build
        env:
          FLAUNCHER_KEYSTORE_PASSWORD: ${{ secrets.FLAUNCHER_KEYSTORE_PASSWORD }}
          FLAUNCHER_SIGNING_KEY_ALIAS: ${{ secrets.FLAUNCHER_SIGNING_KEY_ALIAS }}
          FLAUNCHER_SIGNING_KEY_PASSWORD: ${{ secrets.FLAUNCHER_SIGNING_KEY_PASSWORD }}
          KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: |
          echo -n "$KEYSTORE_FILE_BASE64" | base64 -d > android/app/upload-keystore.jks
          flutter --no-color build apk --split-per-abi
          rename "s/^app-(.*)-release.apk/flauncher-${1}-release.apk/" $OUTPUT_DIR/*.apk
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flauncher-continuous-release
          path: ${{ env.OUTPUT_DIR }}/flauncher-*.apk
          retention-days: 30
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        run: |
          gh release delete continuous --yes
          gh release create continuous --title "Continuous release" $OUTPUT_DIR/flauncher-*.apk
        
